### PR TITLE
Refactor on Validate func

### PR DESCRIPTION
**Pull request by 2hamed**
The `bool` return value was redundant. The validation can be checked just by checking `err`.

### CODE REVIEW

**Comment by ph4r5h4d** [comment]
Hi @2hamed, you are using your other branch to create this branch, all new things should be derived from the master branch.

**Comment by 2hamed** [comment]
Just merge the other one and I'll fix this one after.

**Comment by 2hamed** [comment]
@ph4r5h4d This is fixed now and can be merged.

**Comment by ph4r5h4d** [comment]
Will take care of it today.

**Review by ph4r5h4d — APPROVED** [review]

**Pull request merged**
