### PR TITLE
Add context to check function

### PR DESCRIPTION
**Pull request by fzerorubigd**

### CODE REVIEW

**Comment by fzerorubigd** [comment]
I found a few issues that i need to fix, so I convert it to draft :)

**Review by ph4r5h4d — APPROVED** [review]

**Comment by ph4r5h4d** [comment]
Hey @fzerorubigd, I'm gonna merge it into the develop branch and create another PR to the develop branch to fix the file names.
Later on, I'll spend some time to test it. BTW take a look at https://github.com/ph4r5h4d/wait4it/issues/24, for this project I'm not sure mocking is a good idea, it's better to be tested against real services. the only downside is the tests can't be run on the local machine. Let me know WDYT?

**Comment by ph4r5h4d** [comment]
I'll wait for you then.

**Comment by fzerorubigd** [comment]
There are things that I should fix, but since it is develop branch I guess it is safe to merge this one.

**Pull request merged**
